Traceback (most recent call last):
  File "main_inference.py", line 40, in <module>
    test_dataset = [load_protein_pair(args.single_pdb, single_data_dir,single_pdb=True)]
  File "/disk1/fingerprint/dmasif/data.py", line 373, in load_protein_pair
    y_p1 = p1["y"]
  File "/home/s.joubbi/miniconda3/envs/dmasif/lib/python3.8/site-packages/torch_geometric/data/data.py", line 575, in __getitem__
    return self._store[key]
  File "/home/s.joubbi/miniconda3/envs/dmasif/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 118, in __getitem__
    return self._mapping[key]
KeyError: 'y'
